---
# tasks file for ansible-nfsclient

- name: assert platform
  tags: nfs
  assert:
    that: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
          (ansible_distribution == 'Fedora' and ansible_distribution_major_version == '22') or
          ansible_distribution_release == 'trusty'

- name: Import variables
  tags: nfs
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install packages
  tags: nfs
  become: true
  with_items: nfs_client_pacakges
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"

- name: Create mounts
  tags: nfs
  become: true
  with_items: nfs_mounts
  when: nfs_mounts is defined
  mount:
    state=mounted
    name="{{ nfs_mountpoint_base + '/' +  item.mountpoint if nfs_mountpoint_base is defined else item.mountpoint }}"
    src="{{ nfs_server + ':' + item.src if nfs_server is defined else item.src  }}"
    opts="{{ item.opts|default('rw') }}"
    fstype=nfs
